spring.application.name=rendezvous-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/cabinet_medical_rdv
spring.datasource.username=postgres
spring.datasource.password=pfe123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.consultation_service=DEBUG
springdoc.swagger-ui.path=/swagger-ui.html
rsa.public-key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnNSQWkMwS2a8XVBTwyhK\nLdOojWfj90H+5DA4zU+e7/9tTSbDtsSp0p2eHno5O+ValIHQO2Kf5AflCVkFbcD8\np5yDkMFeFtjtlm1XP+opV0/WvJRSpVWLOATOxVPGQyvylNtaNZ5BRK5b43OlIWhZ\n0mXNKN51CMU0C3jXlAa2LmKAc4Agyg/YGfR0oTlJ1kqgfdujfifOhgcdpQ23IYRu\nYVrh7rVzSfugkJB2rXbglO9YuadcMPJnsUERgRKBvd8NsxjGWBldt97tuYMsQTio\nMvE6XbA9mfglXDqrtDGmhWFUsizbIogVMlGWhUqpTAB3n0715dh2MnKnylCM8w9R\nnQIDAQAB\n-----END PUBLIC KEY-----
spring.main.allow-bean-definition-overriding=true